### PR TITLE
Update suit-install values in the examples and CDDL file

### PR DESCRIPTION
**Pull request by kentakayama**
This PR depends on #23 .

As `suit-install` value in the suit-manifest CDDL definition has been changed in the latest discussion, this PR reflects it.
At this time [the CDDL file](https://github.com/suit-wg/manifest-spec/blob/master/draft-ietf-suit-manifest.cddl#L220) hasn't changed yet, so we replace it with `sed` command.

### CODE REVIEW

**Comment by stoprocent** [comment]
I was wondering as I'm studying the specification now if the examples are correct. From the spec I've understood so far that each component that is a dependency must be referenced by `component-index` in `suit-dependencies` but in the examples there is a single component `'10'` and set-component-index in dependency resolution is setting index to `1`. What am I missing ?

**Comment by kentakayama** [comment]
@stoprocent 
Here are component tables for each SUIT Manifest.

## depending manifest processed by the first Manifest processor
| component-identifier | component-index |
|--|--|
| `['depending.suit']` | N/A |
| `['10']` | 0 in `['depending.suit']` |
| `['dependent.suit']` | 1 in `['depending.suit']` (component-index = 1 in dependencies part) |

```
/ SUIT_Envelope_Tagged / 107({
  / authentication-wrapper / 2: << [
    << [
      / digest-algorithm-id: / -16 / SHA256 /,
      / digest-bytes: / h'DCF344CEF63C615213B669E6FAB48881D154069EE6BD4CD18120935466AA3978'
    ] >>,
    << / COSE_Sign1_Tagged / 18([
      / protected: / << {
        / algorithm-id / 1: -7 / ES256 /
      } >>,
      / unprotected: / {},
      / payload: / null,
      / signature: / h'F86311478A7DCD474700B052CAF14A757CE00709404113B390218E93AE319D564127C4DC3D58CC143FFFB8657E294AA7936B93F51D4A78209479FA66E3186789'
    ]) >>
  ] >>,
  / manifest / 3: << {
    / manifest-version / 1: 1,
    / manifest-sequence-number / 2: 0,
    / common / 3: << {
      / dependencies / 1: {
        / component-index / 1: {
          / dependency-prefix / 1: [
            'dependent.suit'
          ]
        }
      },
      / components / 2: [
        ['10']
      ]
    } >>,
    / manifest-component-id / 5: [
      'depending.suit'
    ],
    / invoke / 9: << [
      / directive-set-component-index / 12, 0,
      / directive-override-parameters / 20, {
        / parameter-invoke-args / 23: 'cat 00 10'
      },
      / directive-invoke / 23, 15
    ] >>,
    / dependency-resolution / 15: << [
      / directive-set-component-index / 12, 1,
      / directive-override-parameters / 20, {
        / parameter-image-digest / 3: << [
          / digest-algorithm-id: / -16 / SHA256 /,
          / digest-bytes: /
            h'CC1758F629D2CDD18698D5A279B532C7003A0331237729C604EE6FD3F3DB535F'
        ] >>,
        / parameter-image-size / 14: 352,
        / parameter-uri / 21: "http://example.com/dependent.suit"
      },
      / directive-fetch / 21, 2,
      / condition-image-match / 3, 15
    ] >>,
    / install / 20: << [
      / directive-set-component-index / 12, 1,
      / directive-override-parameters / 20, {
        / parameter-image-digest / 3: << [
          / digest-algorithm-id: / -16 / SHA256 /,
          / digest-bytes: /
            h'0F02CAF6D3E61920D36BF3CEA7F862A13BB8FB1F09C3F4C29B121FEAB78EF3D8'
        ] >>
      },
      / condition-dependency-integrity / 7, 15,
      / directive-process-dependency / 11, 0,

      / directive-set-component-index / 12, 0,
      / directive-override-parameters / 20, {
        / parameter-content / 18: ' in multiple trust domains'
      },
      / directive-write / 18, 15
    ] >>
  } >>
})
```

## dependent manifest processed by the second Manifest processor
| component-identifier | component-index |
|--|--|
| `['dependent.suit']` | N/A | 
| `['00']` | 0 in `['dependent.suit']` | 

```
/ SUIT_Envelope_Tagged / 107({
  / authentication-wrapper / 2: << [
    << [
      / digest-algorithm-id: / -16 / SHA256 /,
      / digest-bytes: / h'0F02CAF6D3E61920D36BF3CEA7F862A13BB8FB1F09C3F4C29B121FEAB78EF3D8'
    ] >>,
    << / COSE_Sign1_Tagged / 18([
      / protected: / << {
        / algorithm-id / 1: -7 / ES256 /
      } >>,
      / unprotected: / {},
      / payload: / null,
      / signature: / h'D0703EA193E12381A66FFADEF2F0949711CFE05ED2322818D73D19F2BBD91BE5C52F1604B45C405E96B0642F3D49B2D7C6E3B2C0B40030BDDFBD27AF930B1F8B'
    ]) >>
  ] >>,
  / manifest / 3: << {
    / manifest-version / 1: 1,
    / manifest-sequence-number / 2: 0,
    / common / 3: << {
      / components / 2: [
        ['00']
      ]
    } >>,
    / manifest-component-id / 5: [
      'dependent.suit'
    ],
    / invoke / 9: << [
      / directive-override-parameters / 20, {
        / parameter-invoke-args / 23: 'cat 00'
      },
      / directive-invoke / 23, 15
    ] >>,
    / install / 20: << [
      / directive-override-parameters / 20, {
        / parameter-content / 18: 'hello world'
      },
      / directive-write / 18, 15
    ] >>
  } >>
})
```

## How they are processed

1. The first Manifest processor detects the depending Manifest as component-index = 1 while parsing the manifest.common.dependencies section
2. The first Manifest processor detects the component identifier `['10']` as component-index = 0 to be installed by the depending Manifest
3. The first Manifest processor executes the dependency-resolution section, sets the component-index = 1 (dependent Manifest) and fetches it from uri "http://example.com/dependent.suit"
4. The first Manifest processor executes the install section, sets the component-index = 1 (dependent Manifest) and triggers directive-process-dependency
5. The second Manifest processor executes the common and install section, writes the UTF-8 encoded byte string 'hello world' to the component `['00']` (component-index is zero by default) and returns to the first Manifest processor
6. The first Manifest processor sets the component-index = 1 (`['10']`) and writes the UTF-8 encoded byte string 'in multiple trust domains' to the component `['10']`
7. The first Manifest processor executes the invoke section, sets the invoke-args `cat 00 10` and runs it

**Comment by kentakayama** [comment]
Oh, I realized that we need to include the dependent manifest as we removed the delegation chain example from 06 version draft.
You helped me a lot, @stoprocent !

**Comment by stoprocent** [comment]
Thank you! For explanation. I have one more question tho just to make sure I understand:

1. In point 6 of your explanation should be `component-index = 0` right ?
2. I think the RFC part of component indices is not super clear. I thought the rule was that each component has to be specified in the components list and we mark the ones that are dependencies by putting their indices in dependencies array. Can you direct me to a paragraph that explains this? 
3. If I would have a second component in the components array then In order to map `ependency.suit` to an index I would have to set it to 2 in `suit-dependencies`?

**Comment by stoprocent** [comment]
So I went trough spec again and again and all I see is this:

> Because some operations treat Dependency Manifests differently from other Components, it is necessary to identify them. SUIT_Dependencies identifies which Components from suit-components (see Section 8.4.5 of [[I-D.ietf-suit-manifest](https://www.ietf.org/archive/id/draft-ietf-suit-trust-domains-07.html#I-D.ietf-suit-manifest)]) are to be treated as Dependency Manifest Envelopes. SUIT_Dependencies is a map of Components, referenced by Component Index.

So if I understand this correctly for each dependency we need entry in the `suit-components` at the specified index.

**Comment by kentakayama** [comment]
> 1. In point 6 of your explanation should be component-index = 0 right ?

You're right, I'll fix it.

> 2. I think the RFC part of component indices is not super clear. I thought the rule was that each component has to be specified in the components list and we mark the ones that are dependencies by putting their indices in dependencies array. Can you direct me to a paragraph that explains this?

The basic concept of component identifier is in [draft-ietf-suit-manifest](https://datatracker.ietf.org/doc/html/draft-ietf-suit-manifest-27#suit-component-identifier), and it is referenced by [component index](https://datatracker.ietf.org/doc/html/draft-ietf-suit-manifest-27#name-abstract-machine-descriptio).
The [draft-ietf-suit-trust-domains](https://datatracker.ietf.org/doc/html/draft-ietf-suit-trust-domains#name-suit_dependencies-manifest-) adds some commands and extends the [suit-condition-image-match](https://datatracker.ietf.org/doc/html/draft-ietf-suit-trust-domains-07#section-5.2.2-6) command on a component referenced by the component index.

Actually there were a `suit-directive-set-dependency-index` command in [00 draft](https://datatracker.ietf.org/doc/html/draft-ietf-suit-trust-domains-00#section-6.5.2) and a list only for dependencies.
```
SUIT_Dependencies         = [ + SUIT_Dependency ]

SUIT_Dependency = {
    suit-dependency-digest => SUIT_Digest,
    ? suit-dependency-prefix => SUIT_Component_Identifier,
    * $$SUIT_Dependency-extensions,
}
```
But now it is unified into `suit-directive-set-component-index`  because we are now in one conclusion: "**SUIT Manifest can be also a component.**" So dependent manifests are also treated like components.
That's why we introduce [suit-manifest-component-id](https://datatracker.ietf.org/doc/html/draft-ietf-suit-trust-domains-07#name-manifest-component-id) and some can unlink the dependent manifest.

> 3. If I would have a second component in the components array then In order to map ependency.suit to an index I would have to set it to 2 in suit-dependencies?

Right. Though there is no clear mention, but the each component index of dependent manifest should not conflict with other components.
The component indices of dependencies don't conflict each other, since the [CBOR does not allow duplicate keys in a map](https://datatracker.ietf.org/doc/html/rfc8949#section-3.1-2.12).

Correct example
```
    / common / 3: << {
      / dependencies / 1: {
        / component-index / 1: {
          / dependency-prefix / 1: [
            'dependent.suit'
          ]
        }
      },
      / components / 2: [
        ['10']
      ]
    } >>
```

Conflicting example:
```
    / common / 3: << {
      / dependencies / 1: {
        / component-index / 0: { /!!! conflicting with component ['10'] !!!/
          / dependency-prefix / 1: [
            'dependent.suit'
          ]
        }
      },
      / components / 2: [
        ['10']
      ]
    } >>
```

Invalid CBOR example:
```
    / common / 3: << {
      / dependencies / 1: {
        / component-index / 1: {
          / dependency-prefix / 1: [
            'dependent1.suit'
          ]
        },
        / component-index / 1: { /!!! key duplication !!!/
          / dependency-prefix / 1: [
            'dependent2.suit'
          ]
        }
      },
      / components / 2: [
        ['10']
      ]
    } >>
```

**Pull request merged**
